name: longdouble
version: 0.1.0
author: Thomas Stephenson <ovangle@gmail.com>
description: An implementation of a 106 bit floating point data type
homepage: https://github.com/ovangle/longdouble
dev_dependencies:
  unittest: any
