name: longdouble
version: 0.1.0
description: An implementation of a 106 bit floating point data type
homepage: https://github.com/ovangle/longdouble
environment:
  sdk: ">=2.12.0 <4.0.0"
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
